from typing import TypedDict, List, Dict, Any

class AgentState(TypedDict):
    """The state passed between nodes in the LangGraph orchestration graph."""
    messages: List[Dict[str, Any]]          # List of chat messages: [{"role": "user/assistant", "content": "..."}]
    session_id: str                          # Persistent session identifier for SQL/Memory logs
    plan: List[str]                          # Step-by-step resolution plan decided by the Planner
    current_step: int                        # Index of the active step in the plan list
    retrieved_context: List[Dict[str, Any]]  # Document segments retrieved from vector searches
    agent_responses: Dict[str, str]         # Draft answers generated by specialized agents
    response: str                            # Final markdown response sent back to the client
    metrics: Dict[str, Any]                  # Telemetry counters (latency, node execution order)
